### ISSUE TITLE
Missing YAML

### ISSUE THREAD

**Issue by ricksilliker** [bohdon/maya-pulse#1]
```
import pulse.views
pulse.views.togglePulseUI()
Error: ImportError: file /Users/ricksilliker/maya/2017/modules/pulse/scripts/pulse/core.py line 9: No module named yaml
```
Installed pulse on a fresh copy of Maya with no external tools installed. Just seems to be missing yaml from `vendor` I am assuming.

**Comment by bohdon** [comment]
Added yaml to vendor package a46030f
