### ISSUE TITLE
Missing pymetanode

### ISSUE THREAD

**Issue by ricksilliker** [bohdon/maya-pulse#2]
```
import pulse.views
pulse.views.togglePulseUI()
# Error: ImportError: file /Users/ricksilliker/maya/2017/modules/pulse/scripts/pulse/core.py line 12: No module named pymetanode # 
```

Just no mention of needing the module. Like yaml, just expecting dependencies needed to be listed or built into the repo like `Qt.py` is.

**Comment by bohdon** [comment]
added pymetanode to the vendored packages
